version: "3.8"
services:
  localstack:
    image: localstack/localstack:3.2.0
    hostname: localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SERVICES=sns,sqs
    ports:
      - 4566:4566
    volumes:
      - ./localstack-create-resources.sh:/etc/localstack/init/ready.d/create-resources.sh:ro
      - ${TMPDIR:-/tmp/localstack}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
